version: "3"
services:
  rabbit-mq:
    image: rabbitmq:3.9-alpine
    restart: always

  mysql-db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password

  php-my-admin:
    image: phpmyadmin:5.1-apache
    restart: always
    links: 
      - mysql-db:db
    ports: 
      - 8080:80

  api-gateway:
    build: ./api-gateway
    restart: always
    environment: 
      - SERVER_EXT_ADDRESS=${SERVER_EXT_ADDRESS}
    links:
      - mysql-db
      - rabbit-mq
      - service-registry
    ports:
      - 8443:8443
  
  group-request-service:
    build: ./grouprequestservice
    restart: always
    links:
      - mysql-db
      - rabbit-mq
      - service-registry

  individual-request-service:
    build: ./individualrequestservice
    restart: always
    links:
      - mysql-db
      - rabbit-mq
      - service-registry

  service-registry:
    build: ./service-registry
    restart: always

  share-data-service:
    build: ./sharedataservice
    restart: always
    links:
      - mysql-db
      - rabbit-mq
      - service-registry